- hosts: all
  become: true
  vars:
    create_containers: 1
    default_container_name: jenkins-master
    default_container_image: jenkins/jenkins

  tasks:
    - name: Pull Jenkins Image
      docker_image:
        name: "{{default_container_image}}"
        source: pull
    - name: Create Jenkins Networks
      docker_network:
        name: jenkins
    - name: Create Jenkins Data Volume
      docker_volume:
        name: jenkins-data
    - name: Create Jenkins Container
      docker_container:
        name: "{{default_container_name}}"
        image: "{{default_container_image}}"
        ports:
          - "8080:8080"
          - "50000:50000"
        volumes:
          - "jenkins-data:/var/jenkins_home"
        state: started
        recreate: no

